[package]
name = "yew-side-effect"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.18.0", default-features = false, features = ["web_sys"] }
yewtil = "0.4.0"
once_cell = "1.8.0"
